enum ActionEvent {
  LOAD_CATEGORIES = 'LOAD_CATEGORIES',
  RECEIVE_MENU_LIST = 'RECEIVE_MENU_LIST',
  FETCH_USER_INFO = 'FETCH_USER_INFO',
  STORE_USER_INFO = 'STORE_USER_INFO',
}

export default ActionEvent;