dist: xenial
sudo: required

branches:
  only:
    - master
    - dev

addons:
  sonarcloud:
    organization: "s2u2m"
    token:
      secure: "$SONAR_TOKEN"

cache:
  directories:
    - '$HOME/.sonar/cache'
    
matrix:
  include:
    language: node_js
    node_js:
      - '10'
    before_script:
      - cd web
      - npm install
    script:
      - eslint -f json -o eslint-report.json .
      - npm test
    after_script:
      - cd ..
      - sonar-scanner
  