spring:
  profiles:
    active: dev
server:
  port: 7777
s2u2m:
  urlPrefix: /api/v1
  categories:
    -
      name: Test
      dataPath: /home/user/workspace/s2u2m-code/show-me-blog/doc/study/测试
    -
      name: Article
      dataPath: /data/Article