spring:
  profiles:
    active: dev
server:
  port: 7777
s2u2m:
  es:
    nodes:
      - http://localhost:9200
  categories:
    -
      name: Server
      dataPath: /home/user/workspace/s2u2m/show-me-blog/doc/study/server
    -
      name: Test
      dataPath: /home/user/workspace/s2u2m/show-me-blog/doc/study/测试
    -
      name: Web
      dataPath: /home/user/workspace/s2u2m/show-me-blog/doc/study/web