version: '3.7'

services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80" # http
      - "443:443" # https
    volumes:
      - ./nginx/config:/etc/nginx
      - ./nginx/log:/var/log/nginx
      - ./nginx/web/show-me:/usr/share/nginx/show-me
